name: Deploy to produ
on:
  push:
    branches: [main]

jobs:
  push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: push
        run: bash ${GITHUB_WORKSPACE}/run.sh
        shell: bash


  remote-connect:
    runs-on: ubuntu-latest
    needs: push_image
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: 22
          script: sh ./remote_frontend.sh